language: node_js
node_js:
  - 6.7.0

before_install:
  - sudo apt-get update
  - sudo apt-get install g++ build-essential

before_script:
  - python -m SimpleHTTPServer &
  - sleep 2
  - sudo apt-get install xvfb
  - selenium-standalone install
  - sudo xvfb-run --server-args="-screen 0, 1366x768x24" ./node_modules/.bin/selenium-standalone start

cache:
  directories:
    - node_modules

notifications:
  email: false
